#seed - SAME BETWEEN RUNS

#data - SAME BETWEEN RUNS
dataset_dir: "/tmp/ImageNet100C"
dataset: "ImageNet100C"
num_classes: 100
emb_dim: 512

#distributed training - SAME BETWEEN RUNS
num_nodes: 1
gpus: 4
workers: 12
#distributed_backend: "ddp"

###############################################

#Experiment Stuff - CHANGE BETWEEN RUNS
experiment_name: "RN101_CLEAN_100C"
checkpoint_path: "/work2/04703/sravula/maverick2/Logs/Contrastive-Inversion/RN101_CLEAN_LINEAR/checkpoints/epoch=24-step=3099.ckpt"

#Distortions and parameters - CHANGE BETWEEN RUNS
distortion: "None"

saved_model_type: "baseline"

encoder: "resnet"

#logging
log_save_interval: 1 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
logdir: "/tmp/Logs"

results_dir: '/tmp/results_100c'

#validation
check_val_every_n_epoch: 1
