seed: 1234

experiment_name: "birds"

num_nodes: 1
gpus: 1

encoder: "clip"
baseclip_type: "RN101"
device: "cpu"
loss_type: "simclr"

lr: 0.0003
weight_decay: 0.0001
loss_tau: 0.1
logit_scale: 0.07

dataset: "waterbirds"
num_classes: 2

dataset_dir: "/tmp"
logdir: "/tmp"

batch_size: 64

workers: 12

distributed_backend: "dp"

#training
max_epochs: 1
log_save_interval: 1 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
sync_bn: True

#validation
check_val_every_n_epoch: 1
