#seed 
seed: 1234

#data 
dataset_dir: "./dataset/"
dataset: "CIFAR10" #or CIFAR100, STL10, COVID, ImageNet100B
num_classes: 10 # or 100 or 2
emb_dim: 512

#distributed training
num_nodes: 1
gpus: 1
workers: 12

###############################################

#Experiment Stuff 
experiment_name: "sample_transfer_noiselevels"
checkpoint_path: "/path/to/model.ckpt"

#Distortions and parameters 
distortion: "gaussiannoise"
std: 0.1
fixed_mask: False
num_tests: 10
denoised: True # This is used for the experiment in the supplementary

encoder: "clip"
saved_model_type: 'contrastive' # or baseline

#logging
log_save_interval: 10 
row_log_interval: 1
logdir: "/tmp/Logs"

results_dir: './results'

#validation
check_val_every_n_epoch: 1
