seed: 1234

experiment_name: "resnet50_noisyclip_squaremask_50"

num_nodes: 1
gpus: 2

encoder: "resnet"
loss: "contrastive"

distortion: "squaremask"
mask_length: 50

lr: 0.0001
momentum: 0.7
tau: 1
logit_scale: 0.07

dataset: "Imagenet-100"
num_classes: 100
subset_file_name: "imagenet100.txt"

dataset_dir: "../data/imagenet/"
mapping_and_text_file: "./mapping_text_labels_imagenet100.pkl"
save_mapping_and_text: True

batch_size: 100

workers: 12

distributed_backend: "ddp"

#training
max_epochs: 1
log_save_interval: 5 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1

#validation
check_val_every_n_epoch: 5
