#seed
seed: 1234

#Experiment Stuff
experiment_name: "resnet100_baseline_500"

#data
dataset_dir: "../Datasets/ILSVRC/Data/CLS-LOC/"
dataset: "Imagenet-100"
num_classes: 100
subset_file_name: "imagenet100.txt"

distortion: "squaremask" #randommask or squaremask
percent_missing: None #only for randommask
mask_length: 100 #Only for squaremask

#distributed training
num_nodes: 1
gpus: 4
workers: 12
distributed_backend: "ddp"

#model
encoder: "resnet" #'clip' or 'resnet'
clip_model: None #'ViT-B/32' or 'RN50' , only matters if encoder: "clip"
pretrained: True

#training
max_epochs: 500
lr: 0.001
batch_size: 100

#loggind
log_save_interval: 10 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1  

#validation
check_val_every_n_epoch: 5
