#seed - SAME BETWEEN RUNS
seed: 1234

#data - SAME BETWEEN RUNS
dataset_dir: "/tmp/ImageNet100/"
dataset: "ImageNet100"
num_classes: 100
#subset_file_name: "imagenet100.txt"

#distributed training - SAME BETWEEN RUNS
num_nodes: 1
gpus: 4
workers: 12
distributed_backend: "ddp"

###############################################

#Experiment Stuff - CHANGE BETWEEN RUNS
experiment_name: "CLIP_RN50x4_squaretest"

#Distortions and parameters - CHANGE BETWEEN RUNS
distortion: "squaremask" #randommask or squaremask
length: 100 #Only for squaremask

#model - CHANGE BETWEEN RUNS
encoder: "clip" #'clip' or 'resnet'
#resnet_model: "50" #50 or 101
clip_model: 'RN50x4' #'ViT-B/32' or 'RN50' or "RN101" or "RN50x4", only matters if encoder: "clip"
pretrained: True

#training
max_epochs: 1
lr: 0.001
batch_size: 16 #100 for clip RN50, 150 for clip Vit, 64 for clip RN101,     

#logging
log_save_interval: 1 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1  

#validation
check_val_every_n_epoch: 1
