#seed - SAME BETWEEN RUNS
seed: 1234

#data - SAME BETWEEN RUNS
dataset_dir: "/tmp/CIFAR10/"
dataset: "CIFAR10"
num_classes: 10
emb_dim: 512

#distributed training - SAME BETWEEN RUNS
num_nodes: 1
gpus: 4
workers: 12
distributed_backend: "ddp"

###############################################

#Experiment Stuff - CHANGE BETWEEN RUNS
experiment_name: "CLIP_CIFAR10_TRANSFER_CLEAN"
checkpoint_path: "/work2/04703/sravula/maverick2/Logs/Contrastive-Inversion/CLIP_RN101_CLEAN_LINEAR/checkpoints/epoch=24-step=3099.ckpt"

#Distortions and parameters - CHANGE BETWEEN RUNS
distortion: "None" #randommask or squaremask

encoder: "clip"
resnet_model: "RN101" #50 or 101
saved_model_type: 'baseline'

#training
max_epochs: 10
lr: 0.001
batch_size: 128 #100 for clip RN50, 150 for clip Vit, 64 for clip RN101,
use_subset: False

#logging
log_save_interval: 10 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
logdir: "/tmp/Logs"

#validation
check_val_every_n_epoch: 1
