#seed - SAME BETWEEN RUNS

#data - SAME BETWEEN RUNS
dataset_dir: "/tmp/imagenet100_extra/"
dataset: "ImageNet100"
num_classes: 5
emb_dim: 2048

#distributed training - SAME BETWEEN RUNS
num_nodes: 1
gpus: 4
workers: 12
#distributed_backend: "ddp"

###############################################

#Experiment Stuff - CHANGE BETWEEN RUNS
experiment_name: "KD_RANDMANY_OOD"
checkpoint_path: "/work2/04703/sravula/maverick2/Logs/Contrastive-Inversion/KD_RANDMANY/checkpoints/epoch=24-step=12374.ckpt"

#Distortions and parameters - CHANGE BETWEEN RUNS
distortion: "randommask" #randommask or squaremask
noise_levels: [0.5, 0.75,0.8,0.9,0.93,0.95,0.96,0.97, 0.98, 0.99]
fixed_mask: False
saved_model_type: "kd"
num_tests: 10

encoder: "resnet"

#logging
log_save_interval: 25 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
logdir: "/tmp/Logs"

results_dir: '/tmp/resultsKD'

#validation
check_val_every_n_epoch: 1
