#seed - SAME BETWEEN RUNS
seed: 1234

#data - SAME BETWEEN RUNS
dataset_dir: "/tmp/imagenet100_extra/"
dataset: "ImageNet100"
num_classes: 100
emb_dim: 512

#distributed training - SAME BETWEEN RUNS
num_nodes: 1
gpus: 1
workers: 12
distributed_backend: "ddp"

###############################################

#Experiment Stuff - CHANGE BETWEEN RUNS
experiment_name: "sample_noise_level_testing"
checkpoint_path: "/path/to/model.ckpt"

#Distortions and parameters - CHANGE BETWEEN RUNS
distortion: "randommask" #randommask/gaussiannoise/gaussianblur/squaremask
noise_levels: [0.5,0.75,0.9,0.95] # Various noise levels to be tested.
fixed_mask: False
saved_model_type: "linear" #can be linear/zeroshot/baseline

encoder: "clip"

#logging
log_save_interval: 25
row_log_interval: 1
logdir: "/tmp/Logs"

#validation
check_val_every_n_epoch: 1
