seed: 1234

experiment_name: "NOISE05_RN101_CONTRASTIVE_STUDENT_200"

num_nodes: 1
gpus: 4

batch_size: 200

workers: 12

precision: 32

distributed_backend: "dp"

encoder: "resnet"
resnet_model: "101"

loss_type: "simclr"

distortion: "gaussiannoise"
fixed_mask: False
std: 0.5

lr: 0.0003
weight_decay: 0.0001
loss_tau: 0.1

dataset: "Imagenet-100"
num_classes: 100
subset_file_name: "imagenet100.txt"

dataset_dir: "/tmp/ImageNet100"
logdir: "/tmp"

#training
max_epochs: 25
log_save_interval: 25 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
sync_bn: True

#validation
check_val_every_n_epoch: 1
